name: build-toc-json
run-name: ${{ github.actor }} is building the table-of-contents JSON
on: push
jobs:
  build-toc-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install node-dir
      - run: node buildNav
      - name: Configure pull behavior and pull latest changes from remote branch
        run: |
          git config pull.rebase false
          git pull origin new-branch-name
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Merged toc.json
          branch: new-branch-name
