name: build-toc-json
run-name: ${{ github.actor }} is building the table-of-contents JSON
on: push
jobs:
  build-toc-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install node-dir
      - run: node buildNav
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api/toc.json
          git commit -m "Update toc.json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update toc.json
          title: Update toc.json
          body: Update toc.json
